# Generated by Django 5.1.3 on 2024-11-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeblock',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.ManyToManyField(blank=True, default=None, to='level_3.codeblock'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us', to='level_3.user'),
        ),
    ]
