# Generated by Django 5.1.3 on 2024-11-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_3', '0002_remove_codeblock_blog_blog_code_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=12),
        ),
    ]
